version: '3'
services:
  db:
    image: postgres:latest
    container_name: openshield-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=openshield
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - openshield-db-data:/var/lib/postgresql/data

volumes:
  openshield-db-data:
    driver: local