version: '3'
services:
  manager:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://user:pass@db:5432/openshield?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: openshield
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
