// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentTaskService_AssignTask_FullMethodName = "/AgentTaskService/AssignTask"
)

// AgentTaskServiceClient is the client API for AgentTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for agent communication
type AgentTaskServiceClient interface {
	AssignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*AssignTaskResponse, error)
}

type agentTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentTaskServiceClient(cc grpc.ClientConnInterface) AgentTaskServiceClient {
	return &agentTaskServiceClient{cc}
}

func (c *agentTaskServiceClient) AssignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*AssignTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignTaskResponse)
	err := c.cc.Invoke(ctx, AgentTaskService_AssignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentTaskServiceServer is the server API for AgentTaskService service.
// All implementations must embed UnimplementedAgentTaskServiceServer
// for forward compatibility.
//
// Service for agent communication
type AgentTaskServiceServer interface {
	AssignTask(context.Context, *AssignTaskRequest) (*AssignTaskResponse, error)
	mustEmbedUnimplementedAgentTaskServiceServer()
}

// UnimplementedAgentTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentTaskServiceServer struct{}

func (UnimplementedAgentTaskServiceServer) AssignTask(context.Context, *AssignTaskRequest) (*AssignTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTask not implemented")
}
func (UnimplementedAgentTaskServiceServer) mustEmbedUnimplementedAgentTaskServiceServer() {}
func (UnimplementedAgentTaskServiceServer) testEmbeddedByValue()                          {}

// UnsafeAgentTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentTaskServiceServer will
// result in compilation errors.
type UnsafeAgentTaskServiceServer interface {
	mustEmbedUnimplementedAgentTaskServiceServer()
}

func RegisterAgentTaskServiceServer(s grpc.ServiceRegistrar, srv AgentTaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentTaskService_ServiceDesc, srv)
}

func _AgentTaskService_AssignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentTaskServiceServer).AssignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentTaskService_AssignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentTaskServiceServer).AssignTask(ctx, req.(*AssignTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentTaskService_ServiceDesc is the grpc.ServiceDesc for AgentTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AgentTaskService",
	HandlerType: (*AgentTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignTask",
			Handler:    _AgentTaskService_AssignTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent.proto",
}
