name: Test

# This workflow is triggered on pushes to the main branch and on pull requests.
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run tests
        run: go test ./...